### ISSUE TITLE
[1.12.2] "Caught exception from Mystical Agradditions"

### ISSUE THREAD

**Issue by TheSnowyChickens** [BlakeBr0/MysticalAgradditions#75] opened 2021-09-18 03:36 UTC
**Describe the bug**
Hello :=)

Simple and easy = it is a crash on start up, but not all the time.
I restarted the server often and only now, after creating new Advanced Rocketry configs (because the update on the 2.0.0 version) I had this crash 1 time.
After restarting again, all was fine.

**To Reproduce**
Start a 201 mods server ... somehow ... for sure not easy to reproduce.

**Expected behavior**
Clean boot

**Crash Report**
https://pastebin.com/8tyM2G5S

**Versions (please complete the following information):**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2855
 - Cucumber: 1.1.3
 - Mystical Agriculture: 1.7.5
 - Mystical Agradditions: 1.3.2
 
 Ps: I know, it is 1.12.2, but pleeeeaaaaasse don't give up this version, if this is an easy fix. ❤️

**Comment by BlakeBr0** [comment] 2021-11-06 02:53
I'm going to close this since 1.12.2 is EOL. The error in that crash log would not have been caused by anything on my end anyways.

**Closed as completed by BlakeBr0** 2021-11-06 02:53 UTC
Labels: Bug
